[TASK] Adjust initialisation, utilize apache
Also init.sh now switches to supervisord execution like base image,
with custom health check. Apache config is added, and the init.sh
script runs as "root" now and changes its files to "typo3", so it
can dispatch supervisord properly.

A new "contrib-public.yml" image is added that can be used so that
local runs don't need to build their own and would need Dockerfiles.

diff --git a/Dockerfile.contrib b/Dockerfile.contrib
--- a/Dockerfile.contrib
+++ b/Dockerfile.contrib
@@ -3,32 +3,29 @@
 # Uses a host-side(!) GIT checkout and set it up for Core contributions
 # as a composer-based project.
 #
+# @TODO - When finalized, this must go into a readme.
+# @TODO - Adjust github builds
+#
 # Usage:
-#   0.) Have an (empty) working directory with a dummy composer.json:
+#   0.) Have an (empty) working directory:
 #       
-#       $> mkdir ~/TYPO3-Contrib && cd ~/TYPO3-Contrib && touch composer.json
+#       $> mkdir ~/TYPO3-Contrib && cd ~/TYPO3-Contrib
 #
-#   @todo - Put this INTO the container. Use GitHub by default. Offer command to
-#           adjust this from host-side later, when wanting to commit.
-#   1.) Ensure you have a local GIT clone (otherwise the docker image will
-#       complain (replace "XXX" with your my.typo3.org username, that is a
-#       pre-requisite:
-#
-#       $> git clone --branch=main ssh://XXX@review.typo3.org:29418/Packages/TYPO3.CMS.git typo3core
-#
-#   2.) Now you need the `docker-compose.contrib.yml` file, get it from
+#   1.) Now you need the `docker-compose.contrib-public.yml` file, get it from
 #       this repository:
 #
-#       $> wget https://raw.githubusercontent.com/dkd-dobberkau/typo3-base/refs/heads/main/docker-compose.contrib.yml
+#       $> wget https://raw.githubusercontent.com/dkd-dobberkau/typo3-base/refs/heads/main/docker-compose.contrib-public.yml
 #
-#   3.) Now start the docker framework:
+#   2.) Now start the docker framework:
 #
-#       $> docker compose -f docker-compose.contrib.yml up --build
+#       $> docker compose -f docker-compose.contrib-public.yml up
 #
-#   4.) You can require composer packages by editing typo3config/composer.json,
-#       and by entering the web container:
+#   3.) See the logs and access your setup via http://localhost:28080/typo3/
 #
-#       $> docker compose -f docker-compose.contrib.yml exec web composer require "georgringer/news:*"
+#   4.) You can require composer packages by entering the web container to execute "composer" commands
+#       (the `typo3config/composer.json` file will be persisted via mount)
+#
+#       $> docker compose -f docker-compose.contrib-public.yml exec web composer require "georgringer/news:*"
 #
 # =============================================================================
 
@@ -38,21 +35,70 @@ ARG PHP_VERSION=8.2
 # -----------------------------------------------------------------------------
 # Stage 1: Install TYPO3 via Composer
 # -----------------------------------------------------------------------------
-FROM ghcr.io/dkd-dobberkau/base:${PHP_VERSION}-nginx# AS build
+FROM ghcr.io/dkd-dobberkau/base:${PHP_VERSION}-nginx AS build
 
 LABEL org.opencontainers.image.title="TYPO3 Contribution Image"
 LABEL org.opencontainers.image.description="Ready-to-run TYPO3 main contribution setup"
 
-USER typo3
 WORKDIR /var/www/html
 
 # @todo - Make DB Driver configurable
 ENV TYPO3_CONTEXT=Development \
     TYPO3_DB_DRIVER=mysqli
 
-COPY --chmod=755 contrib/init.sh /var/www/html/init.sh
-COPY contrib/composer.json /var/www/html/dist.composer.json
-COPY contrib/gitmessage.txt /var/www/html/dist.gitmessage.txt
+# Minimal subset of docker-entrypoint.sh initialization,
+# note that MAX_EXECUTION_TIME = 0 for contrib/dev setup!
+RUN bash -c '\
+    if [ -f "/etc/php/${PHP_VERSION}/fpm/conf.d/99-typo3.ini" ]; then \
+        sed -i \
+            -e "s|\${PHP_MEMORY_LIMIT}|${PHP_MEMORY_LIMIT:-512M}|g" \
+            -e "s|\${PHP_MAX_EXECUTION_TIME}|${PHP_MAX_EXECUTION_TIME:-0}|g" \
+            -e "s|\${PHP_UPLOAD_MAX_FILESIZE}|${PHP_UPLOAD_MAX_FILESIZE:-32M}|g" \
+            -e "s|\${PHP_POST_MAX_SIZE}|${PHP_POST_MAX_SIZE:-32M}|g" \
+            -e "s|\${PHP_MAX_INPUT_VARS}|${PHP_MAX_INPUT_VARS:-1500}|g" \
+            "/etc/php/${PHP_VERSION}/fpm/conf.d/99-typo3.ini"; \
+    fi && \
+    if [ -f "/etc/php/${PHP_VERSION}/cli/conf.d/99-typo3.ini" ]; then \
+        sed -i \
+            -e "s|\${PHP_MEMORY_LIMIT}|${PHP_MEMORY_LIMIT:-512M}|g" \
+            -e "s|\${PHP_MAX_EXECUTION_TIME}|${PHP_MAX_EXECUTION_TIME:-0}|g" \
+            -e "s|\${PHP_UPLOAD_MAX_FILESIZE}|${PHP_UPLOAD_MAX_FILESIZE:-32M}|g" \
+            -e "s|\${PHP_POST_MAX_SIZE}|${PHP_POST_MAX_SIZE:-32M}|g" \
+            -e "s|\${PHP_MAX_INPUT_VARS}|${PHP_MAX_INPUT_VARS:-1500}|g" \
+            "/etc/php/${PHP_VERSION}/cli/conf.d/99-typo3.ini"; \
+    fi'
+
+# Install Apache with PHP-FPM proxy support
+# hadolint ignore=DL3008
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends apache2; \
+    # Enable required modules
+    a2enmod proxy proxy_fcgi rewrite headers filter expires mime alias deflate setenvif; \
+    # Disable default site
+    a2dissite 000-default; \
+    # Allow Apache (www-data) to access PHP-FPM socket (owned by typo3:typo3)
+    usermod -aG typo3 www-data; \
+    # Cleanup
+    apt-get clean; \
+    rm -rf /var/lib/apt/lists/*
+
+# Apache vhost with AllowOverride All for .htaccess support
+COPY contrib/config/apache/apache-typo3.conf /etc/apache2/sites-available/typo3.conf
+RUN a2ensite typo3
+
+COPY contrib/config/supervisor/supervisord.conf /etc/supervisord.conf
+CMD ["supervisord", "-c", "/etc/supervisord.conf"]
+
+#@todo - This is probably needed for linux; where to set this
+#        so that the handoff to init.sh entrypoint still works?
+#        and the files below (and these by init.sh should be attributed to typo3)
+#USER typo3
+COPY --chown=typo3:typo3 --chmod=755 contrib/init.sh /var/www/html/init.sh
+COPY --chown=typo3:typo3 contrib/composer.json /var/www/html/dist.composer.json
+COPY --chown=typo3:typo3 contrib/gitmessage.txt /var/www/html/dist.gitmessage.txt
+
+EXPOSE 80
 
 ENTRYPOINT ["bash", "/var/www/html/init.sh"]
 
